name: Main Github Actions
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.0
        with:
            node-version: '18.6.0'
      - uses: cypress-io/github-action@v4.2.0
        with:
          config-file: 
            
        
      - name: Merge results
        run: npx mochawesome-merge cypress/report/mochawesome-report/*.json > cypress/report/output.json
        
      - name: Convert results to HTML
        run: npx marge cypress/report/output.json --reportDir ./ --inline        

      - name: Upload reports
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mochawesome
          path: cypress/report
                 
      - name: Publishing Mochawesome artifact to Github Actions
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mochawesome-report
          path: mochawesome-report
          
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: cypress/report
