name: Main Github Actions
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.0
        with:
            node-version: '18.6.0'

      - name: Run test
        run: npm test

      - name: Upload reports
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mochawesome
          path: cypress/report/mochawesome-report
                 
      - name: Publishing Mochawesome artifact to Github Actions
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mochawesome-report
          path: mochawesome-report
          
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: report_default
